import Head from 'next/head';
import { Provider } from 'react-redux';
import { MantineProvider } from '@mantine/core';

import store from '@/store/configureStore';

import { theme } from '@/styles/theme';
import '@/styles/globals.css';

const App = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Jobored</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/assets/favicon.ico' />

      <link rel='preconnect' href='https://fonts.googleapis.com' />
      <link href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap' rel='stylesheet' />
    </Head>
    <Provider store={store}>
      <MantineProvider withGlobalStyles withNormalizeCSS theme={theme}>
        <Component {...pageProps} />
      </MantineProvider>
    </Provider>
  </>
);

export default App;
