import Head from 'next/head';
import { Provider } from 'react-redux';

import authStore from '@/store/configureAuthStore';

import { AppComponent } from '@/components/app/app';

import '@/styles/globals.css';

const App = ({ Component, pageProps }) => (
  <>
    <Head>
      <title>Jobored</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/assets/favicon.ico' />

      <link rel='preconnect' href='https://fonts.googleapis.com' />
      <link href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap' rel='stylesheet' />
    </Head>
    <Provider store={authStore}>
      <AppComponent Component={Component} pageProps={pageProps} />
    </Provider>
  </>
);

export default App;
